### PR TITLE
Attributes

### PR DESCRIPTION
**Pull request by asaunier**
1ad81ae changes the default order of cultures to match the current order in v5 and make appear most used cultures first.

@tsauerwein I have noticed that you have changed this list recently to add activities such as "climbing_multi", "climbing_single", "dry_tool_multi" etc. (see 2057618e8f6cccb928393fa15652c72f77ff422d). In the client PDF (RFP-EtudePreliminaire.pdf > section C10.1), the list of activities is actually:

> 1: skitouring 
>     2: snow_ice_mixed 
>     3: mountain_climbing 
>     4: rock_climbing 
>     5: ice_climbing 
>     6: hiking 
>     7: snowshoeing 
>     8: paragliding 
>     9: moutain_biking 
>    10: via_ferrata

=> it is not considered as for now having activities such as drytooling (included in rock_climbing) or distinguishing multi-pitch/single-pitch/bouldering/etc. in rock_climbing.
I have cancelled your change at 742bf4e

### CODE REVIEW

**Comment by tsauerwein** [comment]
Looks good.

**Comment by asaunier** [comment]
I have upgraded the PR to make more factorizations and simplifications.
Please review.

Since waypoints no longer have an "activities" attribute I have also made a PR in the API to remove it from the model. See https://github.com/c2corg/v6_api/pull/60

**Comment by asaunier** [comment]
@tsauerwein I have changed commit 98f856a in order to use the DEFAULT_\* variables as you suggested.

**Comment by asaunier** [comment]
@tsauerwein I have upgraded the factorization of the WP attributes to use your concatenation trick. See fb8481790b5ebcaf61658505c117d6e28bfbc1df

**Comment by tsauerwein** [comment]
Thanks. That is looking good!

**Pull request merged**
