### PR TITLE
Add field documents_locales.topic_id

### PR DESCRIPTION
**Pull request by arnaud-morvan**

### CODE REVIEW

**Comment by asaunier** [comment]
How are comments in different languages supported?
I think that in v5, comments in different languages are stored in separated topics (the served topic depends on the interface language I think). For me it is not really relevant and all comments could be merged whatever the language.

**Comment by arnaud-morvan** [comment]
Here topic is attached on documents_locales, so we have a different topic for each locale.

**Comment by arnaud-morvan** [comment]
It should be the case in v5 as existing topics are named with document_id and lang.
@gberaudo : can you confirm ?

**Comment by gberaudo** [comment]
Yes

**Comment by asaunier** [comment]
> Here topic is attached on documents_locales, so we have a different topic for each locale.

Right, makes sense!
Looks good, thanks.

**Comment by arnaud-morvan** [comment]
Not needed anymore as we add topic_id in json outside of colander schema. Closing.

**Pull request closed without merging**
