### PR TITLE
add 'creator' to image-view

### PR DESCRIPTION
**Pull request by ginold**

### CODE REVIEW

**Comment by asaunier** [comment]
OK

**Comment by tsauerwein** [comment]
Ehm, does this work?

**Comment by tsauerwein** [comment]
And didn't https://github.com/c2corg/v6_api/pull/380 work for you?

**Comment by ginold** [comment]
well, it had worked and then suddenly stopped, i couldn't load any image-view page because "creator" was undefined (mako error) :confused: then with this it worked again.

**Comment by ginold** [comment]
as if, again, it was saved but not returned. I sometimes see that I upload a new image to a route and then this image doesn't show up in the route-view, but is listed in `internal:routes`. It only shows up after a while and multiple refreshes. 
A cache thing maybe?

**Comment by tsauerwein** [comment]
> well, it had worked and then suddenly stopped, i couldn't load any image-view page because "creator" was undefined (mako error) :confused: then with this it worked again.

You should make sure that you have a clean instance of the API running. Also note that `creator` is only set for the image detail view (not for listings).

> as if, again, it was saved but not returned. I sometimes see that I upload a new image to a route and then this image doesn't show up in the route-view, but is listed in internal:routes. It only shows up after a while and multiple refreshes.
> A cache thing maybe?

What do you mean by `internal:routes`? If you upload an image to a route, an association is created between the image and the route, which will invalidate the cache key for the route. So you shouldn't get an old version from the cache.

**Comment by asaunier** [comment]
Is this unmerged PR still needed?

**Comment by ginold** [comment]
no, indeed.

**Pull request closed without merging**
