### PR TITLE
replace hyphen with minus symbol in route's ratings

### PR DESCRIPTION
**Pull request by ginold**
related to https://github.com/c2corg/v6_ui/issues/922

### CODE REVIEW

**Review by tsauerwein — APPROVED** [review]

**Comment by tsauerwein** [comment]
Will you also update the dependencies in the UI/API project?

**Comment by ginold** [comment]
if this one is approved and if I find the good minus symbol, because for now it tells me that it is not a correct ASCII character :P

**Comment by asaunier** [comment]
Changes are needed here as well:
https://github.com/c2corg/v6_common/blob/master/c2corg_common/sortable_search_attributes.py#L141-L163

and as reported by @tsauerwein in UI and API's `requirements.txt` + in the migration script:
https://github.com/c2corg/v6_api/blob/master/c2corg_api/scripts/migration/documents/routes.py#L261-L283

> if this one is approved and if I find the good minus symbol, because for now it tells me that it is not a correct ASCII character :P

Don't spend too much time on this issue, it's really not critical (and I don't really see the gain).

**Comment by ghost** [comment]
Besides being the proper sign, the gain is that it looks nicer. Sorry (thanks) for the time spent.

http://www.asciitable.com/
196 looks right (not sure)

**Comment by ghost** [comment]
In a text on a V6 page, two hyphens one next to the other turn into a minus sign. 
https://www.demov6.camptocamp.org/routes/diff/822441/fr/1296980/1296988
https://www.demov6.camptocamp.org/routes/822441/fr/iti-test

**Comment by asaunier** [comment]
Could we close this PR?
We have not succeeded in doing this change before the migration. Doing it now would mean to also run an alembic script to adapt all the existing ratings in the database.
For me the difference is so minor that it's not really worth doing it.

**Comment by ghost** [comment]
I'm sure this can wait.


________________________________

**Pull request closed without merging**
