### PR TITLE
remove 'no' from avalanche_signs

### PR DESCRIPTION
**Pull request by ginold**

### CODE REVIEW

**Comment by tsauerwein** [comment]
Are you sure?

**Comment by ginold** [comment]
just discussed with @asaunier and we decided that having a multiple choice selection with "no" inside is not logic - you could select "no avalanches" and "recent avalanches". The client suggested that when "no" is selected, then no other option can be, but it's much more easy to not select anything, when nothing is to be selected. 

But await our last word.

**Comment by tsauerwein** [comment]
> just discussed with @asaunier and we decided that having a multiple choice selection with "no" inside is not logic - you could select "no avalanches" and "recent avalanches".

`no` means "no avalanche signs". You could rename `no` to `no_avalanche_signs`, but this should be handled in the translations.

**Comment by ginold** [comment]
The problem is not the translation but the field itself, which is not really useful. In other cases, when there is NO something, you just don't check anything. So here, if there are no_avalanches, then just don't check the checkbox instead of checking "no" :P

**Comment by tsauerwein** [comment]
In this context `no` means that you have noticed no avalanche signs. This is a useful information and different from not filling out the field at all.

> So here, if there are no_avalanches, then just don't check the checkbox instead of checking "no" :P

Checkbox? This should be a select/radio.

**Comment by ginold** [comment]
> Checkbox? This should be a select/radio.

It is an array `avalanche_signs = Column(ArrayOfEnum(enums.avalanche_signs))`, if not I get an error "xxx is not iterable" and https://docs.google.com/spreadsheets/d/110umbpgS1CUDtzeJ62fNBvn9UBHl_wSbXx5xhFlQTng/edit#gid=792641820 line 39.

Ok, so wait and I will discuss with alex again we will ask the client.

**Comment by tsauerwein** [comment]
> It is an array avalanche_signs = Column(ArrayOfEnum(enums.avalanche_signs)),

Oh yes, you are right.

Also note the remark in the spreadsheet:

> - "aucune observation" ne peut être sélectionné avec une autre option.

**Comment by asaunier** [comment]
> In this context no means that you have noticed no avalanche signs. This is a useful information and different from not filling out the field at all.

That makes sense indeed, I didn't thought about that. So perhaps we should leave the "no" option.
I suggest that we don't implement the conflict check between the "no_avalanche" option and the other ones: it introduces even more complexity.

**Comment by ginold** [comment]
I think I will get it to work as expected, without removing this property. Closing!

**Pull request closed without merging**
